*	This do-file creates transition matrix used for intermediary anlyses
			
			
	*	2 X 2 (FS, FI) - FS status over 4 years 4 years ago (ex. 2001-2005, 2003-2007, ...)			
	cap	mat	drop	trans_2by2_joint_4yrs
	cap	mat	drop	trans_2by2_marginal_4yrs
	
	forvalues	year=3/9	{
					
		local	4year_later	=	`year'+1	
		
		*	Marginal distribution (P_t|P_t-2)
		*	This matrices are generated by multiplying two adjacent 2-by-2 matrices (ex. 2001-2005 = 2001-2003 * 2003-2005)
		
		mat	trans_2by2_marginal_`year'_`4year_later'	=	trans_2by2_marginal_`year' * trans_2by2_marginal_`4year_later'	//	Transition matrix from year to 4 years later		
		mat	trans_2by2_marginal_4yrs	=	nullmat(trans_2by2_marginal_4yrs),	trans_2by2_marginal_`year'_`4year_later'
		
		*	Joint distribution (2-way tabulate)
		svy, subpop(year_enum`4year_later'): tabulate l2_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols	
		mat	trans_2by2_joint_`4year_later' = e(b)[1,1], e(b)[1,2] \ e(b)[1,3], e(b)[1,4]			
		mat	trans_2by2_joint_4yrs	=	nullmat(trans_2by2_joint_4yrs),	trans_2by2_joint_`4year_later'
					
	
	}
	putexcel	A13	=	matrix(trans_2by2_marginal_4yrs), names overwritefmt nformat(number_d1)
	putexcel	A18	=	matrix(trans_2by2_joint_4yrs), names overwritefmt nformat(number_d1)
	

	*	2 X 2 (FS, FI) - FS status over 6 years (ex. 2001-2007, 2003-2009, ...)
	*	This matrices are generated by multiplying three adjacent 2-by-2 matrices (ex. 2001-2007 = 2001-2003 * 2003-2005 * 2003-2005)
	cap	mat	drop	trans_2by2_joint_4yrs
	cap	mat	drop	trans_2by2_marginal_4yrs
	
	forvalues	year=3/8	{
		
		local	4year_later	=	`year'+1
		local	6year_later	=	`year'+2
		
		*	Marginal distribution
		*	This matrices are generated by multiplying three adjacent 2-by-2 matrices (ex. 2001-2007 = 2001-2003 * 2003-2005 * 2003-2005)
		mat	trans_2by2_marginal_`year'_`6year_later'	=	trans_2by2_marginal_`year' * trans_2by2_marginal_`4year_later'	*	trans_2by2_marginal_`6year_later'	//	Transition matrix from year to 4 years later		
		mat	trans_2by2_marginal_6yrs	=	nullmat(trans_2by2_marginal_6yrs),	trans_2by2_marginal_`year'_`6year_later'
		
		*	Joint distribution
		svy, subpop(year_enum`6year_later'): tabulate l3_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols	
		mat	trans_2by2_joint_`6year_later' = e(b)[1,1], e(b)[1,2] \ e(b)[1,3], e(b)[1,4]			
		mat	trans_2by2_joint_6yrs	=	nullmat(trans_2by2_joint_6yrs),	trans_2by2_joint_`6year_later'
	
	}
	putexcel	A23	=	matrix(trans_2by2_marginal_6yrs), names overwritefmt nformat(number_d1)
	putexcel	A28	=	matrix(trans_2by2_joint_6yrs), names overwritefmt nformat(number_d1)
	
	*	2 X 2 (FS, FI) over the entire periods
	cap	mat	drop	trans_2by2_marginal_18years
	cap	mat	drop	trans_2by2_joint_18years
	
		*	Marginal
		forvalues	year=4/10	{
			
			if	`year'==4	{
				mat	trans_2by2_marginal_18years	=	trans_2by2_marginal_3	*	trans_2by2_marginal_`year'
			}
			else	{
				mat	trans_2by2_marginal_18years	=	trans_2by2_marginal_18years	*	trans_2by2_marginal_`year'
			}
			
		}
		
		*	Joint
		svy, subpop(year_enum10): tabulate l8_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols	
		mat	trans_2by2_joint_18years = e(b)[1,1], e(b)[1,2] \ e(b)[1,3], e(b)[1,4]			
	
	putexcel	A33	=	matrix(trans_2by2_marginal_18years), names overwritefmt nformat(number_d1)
	putexcel	A38	=	matrix(trans_2by2_joint_18years), names overwritefmt nformat(number_d1)
	
	*	First-order dependence test
		
		*	Generate state sequence variable (t-2, t-1)
		gen		PFS_ols_FI_FI	=	0	if	!mi(l2_rho1_thrifty_FS_ols)	&	!mi(l1_rho1_thrifty_FS_ols)
		replace	PFS_ols_FI_FI	=	1	if	l2_rho1_thrifty_FS_ols==0	&	l1_rho1_thrifty_FS_ols==0
		
		gen		PFS_ols_FI_FS	=	0	if	!mi(l2_rho1_thrifty_FS_ols)	&	!mi(l1_rho1_thrifty_FS_ols)
		replace	PFS_ols_FI_FS	=	1	if	l2_rho1_thrifty_FS_ols==0	&	l1_rho1_thrifty_FS_ols==1
		
		gen		PFS_ols_FS_FI	=	0	if	!mi(l2_rho1_thrifty_FS_ols)	&	!mi(l1_rho1_thrifty_FS_ols)
		replace	PFS_ols_FS_FI	=	1	if	l2_rho1_thrifty_FS_ols==1	&	l1_rho1_thrifty_FS_ols==0
		
		gen		PFS_ols_FS_FS	=	0	if	!mi(l2_rho1_thrifty_FS_ols)	&	!mi(l1_rho1_thrifty_FS_ols)
		replace	PFS_ols_FS_FS	=	1	if	l2_rho1_thrifty_FS_ols==1	&	l1_rho1_thrifty_FS_ols==1
	
		*	Calculate ratio of 
		svy, subpop(PFS_ols_FI_FI):	tab	rho1_thrifty_FS_ols	//	(FI, FI, FI) & (FI, FI, FS)
		mat	FI_FI_FI	=	e(b)[1,1]
		mat	FI_FI_FS	=	e(b)[1,2]
		svy, subpop(PFS_ols_FI_FS):	tab	rho1_thrifty_FS_ols	//	(FI, FS, FI) & (FI, FS, FS)
		mat	FI_FS_FI	=	e(b)[1,1]
		mat	FI_FS_FS	=	e(b)[1,2]
		svy, subpop(PFS_ols_FS_FI):	tab	rho1_thrifty_FS_ols	//	(FS, FI, FI) & (FS, FI, FS)
		mat	FS_FI_FI	=	e(b)[1,1]
		mat	FS_FI_FS	=	e(b)[1,2]
		svy, subpop(PFS_ols_FS_FS):	tab	rho1_thrifty_FS_ols	//	(FS, FS, FI) & (FS, FS, FS)
		mat	FS_FS_FI	=	e(b)[1,1]
		mat	FS_FS_FS	=	e(b)[1,2]
		
		*	Make a contingency table testing first-order dependence
		*	To hold first-order dependendy, the adjacent rows should have the sample probability (1st & 2nd, 3rd & 4th, 5th & 6th, 7th & 8th)
		mat	first_order_cont_table	=	FI_FI_FI	\	FS_FI_FI	\	FI_FI_FS	\	FS_FI_FS	\	FI_FS_FI	\	FS_FS_FI	\	FI_FS_FS	\	FS_FS_FS
		
		putexcel	A27	=	matrix(first_order_cont_table), names overwritefmt nformat(number_d1)
	
	*	4 X 4 (FS, FI) - Pr(t-1,t|t-2,t-1)
	cap	mat	drop	trans_4by4
	mat	zeros	=	[0,0]
	forvalues	year=4/10	{
		
		svy, subpop(year_enum`year'):	proportion	rho1_thrifty_FS_ols	if	PFS_ols_FI_FI==1	//	Pr(t-1,t|FI, FI)
		mat	FI_FI_`year'	=	e(b),	zeros
		svy, subpop(year_enum`year'):	proportion	rho1_thrifty_FS_ols	if	PFS_ols_FI_FS==1	//	Pr(t-1,t|FI, FS)
		mat	FI_FS_`year'	=	zeros,	e(b)
		svy, subpop(year_enum`year'):	proportion	rho1_thrifty_FS_ols	if	PFS_ols_FS_FI==1	//	Pr(t-1,t|FS, FI)
		mat	FS_FI_`year'	=	e(b),	zeros
		svy, subpop(year_enum`year'):	proportion	rho1_thrifty_FS_ols	if	PFS_ols_FS_FS==1	//	Pr(t-1,t|FS, FS)
		mat	FS_FS_`year'	=	zeros,	e(b)
		
		mat	trans_4by4_`year'	=	FI_FI_`year'	\	FI_FS_`year'	\	FS_FI_`year'	\	FS_FS_`year'
		
		mat	trans_4by4	=	nullmat(trans_4by4),	trans_4by4_`year'
	}

	*putexcel	set "${PSID_outRaw}/Transition_Matrices", sheet(2by2) modify
	*putexcel	A2 = "CPS-PSID Summary Statistics"
	putexcel	E27	=	matrix(trans_4by4), names overwritefmt nformat(number_d1)
}






*	3 X 3 (FS, LFI, VLFI)	-	FS status conditional upon the stataus 2 years ago
	cap	mat	drop	trans_3by3_mgn_2yrs
	cap	mat	drop	trans_3by3_jnt_2yrs
	forvalues	year=3/10	{			
		
		*	Marginal distribution (P_t|P_t-1)
		qui	svy, subpop(year_enum`year'):qui proportion	rho1_thrifty_cat_ols	if	l1_rho1_thrifty_VLFS_ols==1	//	Previously VLFS
		mat	trans_3by3_mgn_`year'_VLFS	=	e(b)
		qui	svy, subpop(year_enum`year'): proportion	rho1_thrifty_cat_ols	if	l1_rho1_thrifty_LFS_ols==1	//	Previously LFS
		mat	trans_3by3_mgn_`year'_LFS	=	e(b)
		qui	svy, subpop(year_enum`year'): proportion	rho1_thrifty_cat_ols	if	l1_rho1_thrifty_FS_ols==1	//	Previously FS
		mat	trans_3by3_mgn_`year'_FS	=	e(b)
		
		mat	trans_3by3_mgn_`year'	=	trans_3by3_mgn_`year'_VLFS	\	trans_3by3_mgn_`year'_LFS	\		trans_3by3_mgn_`year'_FS		
		mat	trans_3by3_mgn_2yrs	=	nullmat(trans_3by3_mgn_2yrs),	trans_3by3_mgn_`year'
		
		*	Joint distribution	(two-way tabulate)
		svy, subpop(year_enum`year'): tabulate l1_rho1_thrifty_cat_ols	rho1_thrifty_cat_ols
		mat	trans_3by3_jnt_`year' = e(b)[1,1], e(b)[1,2], e(b)[1,3]	\ e(b)[1,4], e(b)[1,5],	e(b)[1,6]	\	e(b)[1,7],	e(b)[1,8],	e(b)[1,9]	
		mat	trans_3by3_jnt_2yrs	=	nullmat(trans_3by3_jnt_2yrs),	trans_3by3_jnt_`year'
		
	}
	
	putexcel	set "${PSID_outRaw}/Transition_Matrices", sheet(3by3) replace	/*modify*/
	putexcel	A3	=	matrix(trans_3by3_mgn_2yrs), names overwritefmt nformat(number_d1)
	putexcel	A8	=	matrix(trans_3by3_jnt_2yrs), names overwritefmt nformat(number_d1)
	
*	3 X 3 (FS, LFS, VLFS) - FS status over 4 years (ex. 2001-2005, 2003-2007, ...)			
	cap	mat	drop	trans_3by3_jnt_4yrs
	cap	mat	drop	trans_3by3_mgn_4yrs
	
	forvalues	year=3/9	{
					
		local	4year_later	=	`year'+1	
		
		*	Marginal distribution (P_t|P_t-2)
		*	This matrices are generated by multiplying two adjacent 2-by-2 matrices (ex. 2001-2005 = 2001-2003 * 2003-2005)
		
		mat	trans_3by3_mgn_`year'_`4year_later'	=	trans_3by3_mgn_`year' * trans_3by3_mgn_`4year_later'	//	Transition matrix from year to 4 years later		
		mat	trans_3by3_mgn_4yrs	=	nullmat(trans_3by3_mgn_4yrs),	trans_3by3_mgn_`year'_`4year_later'
		
		*	Joint distribution (2-way tabulate)
		svy, subpop(year_enum`4year_later'): tabulate l2_rho1_thrifty_cat_ols	rho1_thrifty_cat_ols	
		mat	trans_3by3_jnt_`4year_later' = e(b)[1,1], e(b)[1,2], e(b)[1,3]	\ e(b)[1,4], e(b)[1,5],	e(b)[1,6]	\	e(b)[1,7],	e(b)[1,8],	e(b)[1,9]		
		mat	trans_3by3_jnt_4yrs	=	nullmat(trans_3by3_jnt_4yrs),	trans_3by3_jnt_`4year_later'
					
	
	}
	putexcel	A13	=	matrix(trans_3by3_mgn_4yrs), names overwritefmt nformat(number_d1)
	putexcel	A18	=	matrix(trans_3by3_jnt_4yrs), names overwritefmt nformat(number_d1)

*	2 X 2 (FS, FI) over the entire periods
	cap	mat	drop	trans_3by3_mgn_18years
	cap	mat	drop	trans_3by3_jnt_18years
	
		*	Marginal
		forvalues	year=4/10	{
			
			if	`year'==4	{
				mat	trans_3by3_mgn_18years	=	trans_3by3_mgn_3	*	trans_3by3_mgn_`year'
			}
			else	{
				mat	trans_3by3_mgn_18years	=	trans_3by3_mgn_18years	*	trans_3by3_mgn_`year'
			}
			
		}
		
		*	Joint
		svy, subpop(year_enum10): tabulate l8_rho1_thrifty_cat_ols	rho1_thrifty_cat_ols	
		mat	trans_3by3_jnt_18years = e(b)[1,1], e(b)[1,2], e(b)[1,3]	\ e(b)[1,4], e(b)[1,5],	e(b)[1,6]	\	e(b)[1,7],	e(b)[1,8],	e(b)[1,9]				
	
	putexcel	A33	=	matrix(trans_3by3_mgn_18years), names overwritefmt nformat(number_d1)
	putexcel	A38	=	matrix(trans_3by3_jnt_18years), names overwritefmt nformat(number_d1)	
	
* Transition matrix by age

mat	drop	_all
cap drop min_age	max_age	became_65	under_65	dev_from_65	became_retired	year_retired	retired_during_study	noretire_during_study	dev_from_retireage	

bys	fam_ID_1999: egen min_age = min(age_head_fam)
bys	fam_ID_1999: egen max_age = max(age_head_fam)

*	Became 65 during the study period
gen		became_65	=	1	if	min_age<65	&	max_age>=65
replace	became_65	=	0	if	max_age<65	|	min_age>=65

*	Under 65 during the study period
gen		under_65	=	1	if	max_age<65
replace	under_65	=	0	if	max_age>=65

gen	dev_from_65	=	(65-age_head_fam)	if	became_65==1

*	Retired during the study period
	
	*	Became retired
	gen		became_retired	=	1	if	inrange(l.emp_status_head,1,3)	&	emp_status_head==4	&	year!=1	//	became retired
	replace	became_retired	=	0	if	became_retired!=1
	gen		year_retired	=	year2	if	became_retired==1	//	retired year (during the study period)
	
	*	Became retired at least once during the study period
	bys	fam_ID_1999:	egen	retired_during_study	=	max(became_retired)	//	became retired during the study period
	bys	fam_ID_1999:	egen	year_became_retired		=	min(year_retired)	if	retired_during_study==1	//	year retired during the study period (if multiple, the earlierst retirement)
	
	*	Not retired during the study period
	gen		noretire_during_study	=	1	if	retired_during_study==0
	replace	noretire_during_study	=	0	if	retired_during_study==1

	gen	dev_from_retireage	=	(year2 -	year_became_retired )	if	retired_during_study==1

*	Transition matrix, retired_during_study

	*	Pooled, marginal
	svy, subpop(became_65): proportion	rho1_thrifty_FS_ols	if	l1_rho1_thrifty_FS_ols==0	&	inrange(dev_from_retireage,1,20)	//	Before retire, Previously FI
	mat	trans_2by2_mgn_pre65_FI		=	e(b)
	svy, subpop(became_65): proportion	rho1_thrifty_FS_ols	if	l1_rho1_thrifty_FS_ols==1	&	inrange(dev_from_retireage,1,20)	//	Before retire, Previously FS
	mat	trans_2by2_mgn_pre65_FS		=	e(b)
	svy, subpop(became_65): proportion	rho1_thrifty_FS_ols	if	l1_rho1_thrifty_FS_ols==0	&	inrange(dev_from_retireage,-20,0)	//	After retire, Previously FI
	mat	trans_2by2_mgn_post65_FI	=	e(b)
	svy, subpop(became_65): proportion	rho1_thrifty_FS_ols	if	l1_rho1_thrifty_FS_ols==1	&	inrange(dev_from_retireage,-20,0)	//	After retire, Previously FS
	mat	trans_2by2_mgn_post65_FS	=	e(b)

	mat	trans_2by2_mgn_pre65	=	trans_2by2_mgn_pre65_FI	\	trans_2by2_mgn_pre65_FS
	mat	trans_2by2_mgn_post65	=	trans_2by2_mgn_post65_FI	\	trans_2by2_mgn_post65_FS

	mat	trans_2by2_mgn_age65	=	trans_2by2_mgn_pre65,	trans_2by2_mgn_post65

	*	Pooled, joint
	svy, subpop(became_65):	tab l1_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols	if inrange(dev_from_65,1,20)	//	64- years old
	mat	trans_2by2_jnt_pre65 = e(b)[1,1], e(b)[1,2] \ e(b)[1,3], e(b)[1,4]
	svy, subpop(became_65):	tab l1_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols	if inrange(dev_from_65,-20,0)	//	65+ years old
	mat	trans_2by2_jnt_post65 = e(b)[1,1], e(b)[1,2] \ e(b)[1,3], e(b)[1,4]

	mat	trans_2by2_jnt_age65	=	trans_2by2_jnt_pre65,	trans_2by2_jnt_post65
	
	*	By year
	cap	mat	drop	trans_2by2_mgn_byyear_FI	trans_2by2_mgn_byyear_FS
	forvalues	year=0(-2)-10	{
		
		local	max_year=`year'
		if	`year'==-10	{
			local	min_year=-20
		}
		else	{
			local	min_year=`year'-1
		}
		*di "min_year is `min_year', max_year is `max_year'"
		
		*	Marginal
		svy, subpop(became_65):	proportion	rho1_thrifty_FS_ols	///
			if	l1_rho1_thrifty_FS_ols==0	&	inrange(dev_from_65,`min_year',`max_year')	//	Previously FI
		mat	trans_2by2_mgn_byyear_FI	=	nullmat(trans_2by2_mgn_byyear_FI),	e(b)
		svy, subpop(became_65):	proportion	rho1_thrifty_FS_ols	///
			if	l1_rho1_thrifty_FS_ols==1	&	inrange(dev_from_65,`min_year',`max_year')	//	Previously FS
		mat	trans_2by2_mgn_byyear_FS	=	nullmat(trans_2by2_mgn_byyear_FS),	e(b)
		
		*	Joint
		svy, subpop(became_65):	tab	l1_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols	if inrange(dev_from_65,`min_year',`max_year')
		mat	trans_2by2_jnt_byyear_FI = nullmat(trans_2by2_jnt_byyear_FI), e(b)[1,1], e(b)[1,2]
		mat	trans_2by2_jnt_byyear_FS = nullmat(trans_2by2_jnt_byyear_FS), e(b)[1,3], e(b)[1,4]	
		
	}
	mat	trans_2by2_mgn_byyear	=	trans_2by2_mgn_byyear_FI	\	trans_2by2_mgn_byyear_FS
	mat	trans_2by2_jnt_byyear	=	trans_2by2_jnt_byyear_FI	\	trans_2by2_jnt_byyear_FS
	
*	Transition matrix, under 65

	*	Pooled, marginal
	svy, subpop(under_65): proportion	rho1_thrifty_FS_ols	if	l1_rho1_thrifty_FS_ols==0	//	Under 65, Previously FI
	mat	trans_2by2_mgn_under65_FI		=	e(b)
	svy, subpop(under_65): proportion	rho1_thrifty_FS_ols	if	l1_rho1_thrifty_FS_ols==1	//	Under 65, Previously FS
	mat	trans_2by2_mgn_under65_FS		=	e(b)
	
	mat	trans_2by2_mgn_under65	=	trans_2by2_mgn_under65_FI	\	trans_2by2_mgn_under65_FS
	
	*	Pooled, joint
	svy, subpop(under_65):	tab l1_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols	//	64- years old
	mat	trans_2by2_jnt_under65 = e(b)[1,1], e(b)[1,2] \ e(b)[1,3], e(b)[1,4]

	putexcel	set "${PSID_outRaw}/Transition_Matrices", sheet(2by2_age) replace	/*modify*/
	putexcel	A3	=	matrix(trans_2by2_mgn_age65), names overwritefmt nformat(number_d1)
	putexcel	A8	=	matrix(trans_2by2_jnt_age65), names overwritefmt nformat(number_d1)
	putexcel	A13	=	matrix(trans_2by2_mgn_byyear), names overwritefmt nformat(number_d1)
	putexcel	A18	=	matrix(trans_2by2_jnt_byyear), names overwritefmt nformat(number_d1)
	putexcel	A23	=	matrix(trans_2by2_mgn_under65), names overwritefmt nformat(number_d1)
	putexcel	A28	=	matrix(trans_2by2_jnt_under65), names overwritefmt nformat(number_d1)
	
	
*	Transition matrix, became retired

		*	Marginal
	svy, subpop(retired_during_study): proportion	rho1_thrifty_FS_ols	if	l1_rho1_thrifty_FS_ols==0	&	inrange(dev_from_retireage,1,20)	//	Before retire, Previously FI
	mat	trans_2by2_mgn_preretire_FI		=	e(b)
	svy, subpop(retired_during_study): proportion	rho1_thrifty_FS_ols	if	l1_rho1_thrifty_FS_ols==1	&	inrange(dev_from_retireage,1,20)	//	Before retire, Previously FS
	mat	trans_2by2_mgn_preretire_FS		=	e(b)
	svy, subpop(retired_during_study): proportion	rho1_thrifty_FS_ols	if	l1_rho1_thrifty_FS_ols==0	&	inrange(dev_from_retireage,-20,0)	//	After retire, Previously FI
	mat	trans_2by2_mgn_postretire_FI	=	e(b)
	svy, subpop(retired_during_study): proportion	rho1_thrifty_FS_ols	if	l1_rho1_thrifty_FS_ols==1	&	inrange(dev_from_retireage,-20,0)	//	After retire, Previously FS
	mat	trans_2by2_mgn_postretire_FS	=	e(b)

	mat	trans_2by2_mgn_preretire	=	trans_2by2_mgn_preretire_FI	\	trans_2by2_mgn_preretire_FS
	mat	trans_2by2_mgn_postretire	=	trans_2by2_mgn_postretire_FI	\	trans_2by2_mgn_postretire_FS

	mat	trans_2by2_mgn_retire	=	trans_2by2_mgn_preretire,	trans_2by2_mgn_postretire

	*	Joint
	svy, subpop(retired_during_study):	tab l1_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols	if inrange(dev_from_retireage,1,20)	//	
	mat	trans_2by2_jnt_preretire = e(b)[1,1], e(b)[1,2] \ e(b)[1,3], e(b)[1,4]
	svy, subpop(retired_during_study):	tab l1_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols	if inrange(dev_from_retireage,-20,0)	//	
	mat	trans_2by2_jnt_postretire = e(b)[1,1], e(b)[1,2] \ e(b)[1,3], e(b)[1,4]

	mat	trans_2by2_jnt_retire	=	trans_2by2_jnt_preretire,	trans_2by2_jnt_postretire
	
	*	By year
	cap	mat	drop	trans_2by2_ret_mgn_byyear_FI	trans_2by2_ret_mgn_byyear_FS	trans_2by2_ret_jnt_byyear_FI	trans_2by2_ret_jnt_byyear_FS
	forvalues	year=0(-2)-10	{
		
		local	max_year=`year'
		if	`year'==-10	{
			local	min_year=-20
		}
		else	{
			local	min_year=`year'-1
		}
		*di "min_year is `min_year', max_year is `max_year'"
		
		*	Marginal
		svy, subpop(retired_during_study):	proportion	rho1_thrifty_FS_ols	///
			if	l1_rho1_thrifty_FS_ols==0	&	inrange(dev_from_retireage,`min_year',`max_year')	//	Previously FI
		mat	trans_2by2_ret_mgn_byyear_FI	=	nullmat(trans_2by2_ret_mgn_byyear_FI),	e(b)
		svy, subpop(retired_during_study):	proportion	rho1_thrifty_FS_ols	///
			if	l1_rho1_thrifty_FS_ols==1	&	inrange(dev_from_retireage,`min_year',`max_year')	//	Previously FS
		mat	trans_2by2_ret_mgn_byyear_FS	=	nullmat(trans_2by2_ret_mgn_byyear_FS),	e(b)
		
		*	Joint
		svy, subpop(retired_during_study):	tab	l1_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols	if inrange(dev_from_retireage,`min_year',`max_year')
		mat	trans_2by2_ret_jnt_byyear_FI = nullmat(trans_2by2_ret_jnt_byyear_FI), e(b)[1,1], e(b)[1,2]
		mat	trans_2by2_ret_jnt_byyear_FS = nullmat(trans_2by2_ret_jnt_byyear_FS), e(b)[1,3], e(b)[1,4]	
		
	}
	mat	trans_2by2_ret_mgn_byyear	=	trans_2by2_ret_mgn_byyear_FI	\	trans_2by2_ret_mgn_byyear_FS
	mat	trans_2by2_ret_jnt_byyear	=	trans_2by2_ret_jnt_byyear_FI	\	trans_2by2_ret_jnt_byyear_FS
	
	*	No retire, pooled
	*	marginal
	svy, subpop(noretire_during_study): proportion	rho1_thrifty_FS_ols	if	l1_rho1_thrifty_FS_ols==0	//	No retire, Previously FI
	mat	trans_2by2_mgn_noretire_FI		=	e(b)
	svy, subpop(noretire_during_study): proportion	rho1_thrifty_FS_ols	if	l1_rho1_thrifty_FS_ols==1	//	No retire, Previously FS
	mat	trans_2by2_mgn_noretire_FS		=	e(b)
	
	mat	trans_2by2_mgn_noretire	=	trans_2by2_mgn_noretire_FI	\	trans_2by2_mgn_noretire_FS
	
	*	joint
	svy, subpop(noretire_during_study):	tab l1_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols	//	No retire
	mat	trans_2by2_jnt_noretire = e(b)[1,1], e(b)[1,2] \ e(b)[1,3], e(b)[1,4]
	

	putexcel	set "${PSID_outRaw}/Transition_Matrices", sheet(2by2_age) modify	/*replace*/
	putexcel	A33	=	matrix(trans_2by2_mgn_retire), names overwritefmt nformat(number_d1)
	putexcel	A38	=	matrix(trans_2by2_jnt_retire), names overwritefmt nformat(number_d1)
	putexcel	A43	=	matrix(trans_2by2_ret_mgn_byyear), names overwritefmt nformat(number_d1)
	putexcel	A48	=	matrix(trans_2by2_ret_jnt_byyear), names overwritefmt nformat(number_d1)
	putexcel	A53	=	matrix(trans_2by2_mgn_noretire), names overwritefmt nformat(number_d1)
	putexcel	A58	=	matrix(trans_2by2_jnt_noretire), names overwritefmt nformat(number_d1)

	
*	Gender
	
	*	Marginal
	svy, subpop(gender_head_fam):	proportion	rho1_thrifty_FS_ols		if	l1_rho1_thrifty_FS_ols==0	//	Previously FI, male
	mat	trans_2by2_mgn_male_FI		=	e(b)
	svy, subpop(gender_head_fam):	proportion	rho1_thrifty_FS_ols		if	l1_rho1_thrifty_FS_ols==1	//	Previously FS, male
	mat	trans_2by2_mgn_male_FS		=	e(b)
	svy, subpop(HH_female):	proportion	rho1_thrifty_FS_ols		if	l1_rho1_thrifty_FS_ols==0	//	Previously FI, female
	mat	trans_2by2_mgn_female_FI		=	e(b)
	svy, subpop(HH_female):	proportion	rho1_thrifty_FS_ols		if	l1_rho1_thrifty_FS_ols==1	//	Previously FS, female
	mat	trans_2by2_mgn_female_FS		=	e(b)
	
	mat	trans_2by2_mgn_male	=	trans_2by2_mgn_male_FI	\	trans_2by2_mgn_male_FS
	mat	trans_2by2_mgn_female	=	trans_2by2_mgn_female_FI	\	trans_2by2_mgn_female_FS
	
	mat	trans_2by2_mgn_gender	=	trans_2by2_mgn_male	,	trans_2by2_mgn_female
	
	*	Joint
	svy, subpop(gender_head_fam):	tab	l1_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols
	mat	trans_2by2_jnt_male = e(b)[1,1], e(b)[1,2] \ e(b)[1,3], e(b)[1,4]
	svy, subpop(HH_female):	tab	l1_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols
	mat	trans_2by2_jnt_female = e(b)[1,1], e(b)[1,2] \ e(b)[1,3], e(b)[1,4]
	
	mat	trans_2by2_jnt_gender	=	trans_2by2_jnt_male,	trans_2by2_jnt_female
	
	putexcel	set "${PSID_outRaw}/Transition_Matrices", sheet(2by2_characters) modify	/*replace*/
	putexcel	A63	=	matrix(trans_2by2_mgn_gender), names overwritefmt nformat(number_d1)
	putexcel	A68	=	matrix(trans_2by2_jnt_gender), names overwritefmt nformat(number_d1)


*	Race

	*	Marginal
	svy, subpop(HH_race_white):	proportion	rho1_thrifty_FS_ols		if	l1_rho1_thrifty_FS_ols==0	//	Previously FI, white
	mat	trans_2by2_mgn_white_FI		=	e(b)
	svy, subpop(HH_race_white):	proportion	rho1_thrifty_FS_ols		if	l1_rho1_thrifty_FS_ols==1	//	Previously FS, white
	mat	trans_2by2_mgn_white_FS		=	e(b)
	svy, subpop(HH_race_black):	proportion	rho1_thrifty_FS_ols		if	l1_rho1_thrifty_FS_ols==0	//	Previously FI, black
	mat	trans_2by2_mgn_black_FI		=	e(b)
	svy, subpop(HH_race_black):	proportion	rho1_thrifty_FS_ols		if	l1_rho1_thrifty_FS_ols==1	//	Previously FS, black
	mat	trans_2by2_mgn_black_FS		=	e(b)
	svy, subpop(HH_race_other):	proportion	rho1_thrifty_FS_ols		if	l1_rho1_thrifty_FS_ols==0	//	Previously FS, other
	mat	trans_2by2_mgn_other_FI		=	e(b)
	svy, subpop(HH_race_other):	proportion	rho1_thrifty_FS_ols		if	l1_rho1_thrifty_FS_ols==1	//	Previously FS, other
	mat	trans_2by2_mgn_other_FS		=	e(b)
	
	mat	trans_2by2_mgn_white	=	trans_2by2_mgn_white_FI	\	trans_2by2_mgn_white_FS
	mat	trans_2by2_mgn_black	=	trans_2by2_mgn_black_FI	\	trans_2by2_mgn_black_FS
	mat	trans_2by2_mgn_other	=	trans_2by2_mgn_other_FI	\	trans_2by2_mgn_other_FS
	
	mat	trans_2by2_mgn_race	=	trans_2by2_mgn_white	,	trans_2by2_mgn_black,	trans_2by2_mgn_other
	
	*	Joint
	svy, subpop(HH_race_white):	tab	l1_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols
	mat	trans_2by2_jnt_white = e(b)[1,1], e(b)[1,2] \ e(b)[1,3], e(b)[1,4]
	svy, subpop(HH_race_black):	tab	l1_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols
	mat	trans_2by2_jnt_black = e(b)[1,1], e(b)[1,2] \ e(b)[1,3], e(b)[1,4]
	svy, subpop(HH_race_other):	tab	l1_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols
	mat	trans_2by2_jnt_other = e(b)[1,1], e(b)[1,2] \ e(b)[1,3], e(b)[1,4]
	
	mat	trans_2by2_jnt_race	=	trans_2by2_jnt_white,	trans_2by2_jnt_black,	trans_2by2_jnt_other
	
	putexcel	set "${PSID_outRaw}/Transition_Matrices", sheet(2by2_characters) modify	/*replace*/
	putexcel	A73	=	matrix(trans_2by2_mgn_race), names overwritefmt nformat(number_d1)
	putexcel	A78	=	matrix(trans_2by2_jnt_race), names overwritefmt nformat(number_d1)
	

*	Pre-/post- recession

	cap	drop	pre_recession post_recession
	gen		pre_recession	=	0
	replace	pre_recession	=	1	if	inrange(year,1,5)	//	Wave 1999 to 2007
	gen		post_recession	=	0
	replace	post_recession	=	1	if	inrange(year,6,10)	//	Wave 2009 to 2017
	
	cap	mat	drop	trans_2by2_mgn_recession	trans_2by2_jnt_recession	
	
	foreach	category	in	pre_recession	post_recession	{
		
		*	Marginal
		svy, subpop(`category'):	proportion	rho1_thrifty_FS_ols		if	l1_rho1_thrifty_FS_ols==0	//	Previously FI, white
		mat	trans_2by2_mgn_`category'_FI		=	e(b)
		svy, subpop(`category'):	proportion	rho1_thrifty_FS_ols		if	l1_rho1_thrifty_FS_ols==1	//	Previously FS, white
		mat	trans_2by2_mgn_`category'_FS		=	e(b)
		
		mat	trans_2by2_mgn_`category'	=	trans_2by2_mgn_`category'_FI	\	trans_2by2_mgn_`category'_FS
		mat	trans_2by2_mgn_recession	=	nullmat(trans_2by2_mgn_recession),	trans_2by2_mgn_`category'
		
		*	Joint
		svy, subpop(`category'):	tab	l1_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols
		mat	trans_2by2_jnt_`category' = e(b)[1,1], e(b)[1,2] \ e(b)[1,3], e(b)[1,4]
		mat	trans_2by2_jnt_recession	=	nullmat(trans_2by2_jnt_recession),	trans_2by2_jnt_`category'
	}
	
	putexcel	set "${PSID_outRaw}/Transition_Matrices", sheet(2by2_characters) modify	/*replace*/
	putexcel	A83	=	matrix(trans_2by2_mgn_recession), names overwritefmt nformat(number_d1)
	putexcel	A88	=	matrix(trans_2by2_jnt_recession), names overwritefmt nformat(number_d1)
	
*	Disabled
	
	cap	drop	disabled	non_disabled
	clonevar	disabled	=	phys_disab_head
	gen		non_disabled	=	1	if	phys_disab_head==0
	replace	non_disabled	=	0	if	phys_disab_head==1
	
	cap	mat	drop	trans_2by2_mgn_disability	trans_2by2_jnt_disability	
	
	foreach	category	in	disabled	non_disabled	{
		
		*	Marginal
		svy, subpop(`category'):	proportion	rho1_thrifty_FS_ols		if	l1_rho1_thrifty_FS_ols==0	//	Previously FI, white
		mat	trans_2by2_mgn_`category'_FI		=	e(b)
		svy, subpop(`category'):	proportion	rho1_thrifty_FS_ols		if	l1_rho1_thrifty_FS_ols==1	//	Previously FS, white
		mat	trans_2by2_mgn_`category'_FS		=	e(b)
		
		mat	trans_2by2_mgn_`category'	=	trans_2by2_mgn_`category'_FI	\	trans_2by2_mgn_`category'_FS
		mat	trans_2by2_mgn_disability	=	nullmat(trans_2by2_mgn_disability),	trans_2by2_mgn_`category'
		
		*	Joint
		svy, subpop(`category'):	tab	l1_rho1_thrifty_FS_ols	rho1_thrifty_FS_ols
		mat	trans_2by2_jnt_`category' = e(b)[1,1], e(b)[1,2] \ e(b)[1,3], e(b)[1,4]
		mat	trans_2by2_jnt_disability	=	nullmat(trans_2by2_jnt_disability),	trans_2by2_jnt_`category'
	}
	
	putexcel	set "${PSID_outRaw}/Transition_Matrices", sheet(2by2_characters) modify	/*replace*/
	putexcel	A93	=	matrix(trans_2by2_mgn_disability), names overwritefmt nformat(number_d1)
	putexcel	A98	=	matrix(trans_2by2_jnt_disability), names overwritefmt nformat(number_d1)
	
*	Received food stamp
	
	cap	drop	stamp	no_stamp
	clonevar	stamp	=	food_stamp_used_1yr
	gen		no_stamp	=	1	if	stamp==0
	replace	no_stamp	=	0	if	stamp==1
	
	cap	mat	drop	trans_3by3_mgn_foodstamp	trans_3by3_jnt_foodstamp	trans_3by3_mgn_foodstamp_f	trans_3by3_jnt_foodstamp_f
	
	foreach	category	in	stamp	no_stamp	{
				
		*	Marginal distribution (P_t|P_t-1)
		qui	svy, subpop(`category'): proportion	rho1_thrifty_cat_ols	if	l1_rho1_thrifty_VLFS_ols==1	//	Previously VLFS
		mat	trans_3by3_mgn_`category'_VLFS	=	e(b)
		qui	svy, subpop(`category'): proportion	rho1_thrifty_cat_ols	if	l1_rho1_thrifty_LFS_ols==1	//	Previously LFS
		mat	trans_3by3_mgn_`category'_LFS	=	e(b)
		qui	svy, subpop(`category'): proportion	rho1_thrifty_cat_ols	if	l1_rho1_thrifty_FS_ols==1	//	Previously FS
		mat	trans_3by3_mgn_`category'_FS	=	e(b)
		
		mat	trans_3by3_mgn_`category'	=	trans_3by3_mgn_`category'_VLFS	\	trans_3by3_mgn_`category'_LFS	\		trans_3by3_mgn_`category'_FS		
		mat	trans_3by3_mgn_foodstamp	=	nullmat(trans_3by3_mgn_foodstamp),	trans_3by3_mgn_`category'
		
		*	Marginal distribution (P_t+1|P_t)
		qui	svy, subpop(`category'): proportion	f1_rho1_thrifty_cat_ols	if	rho1_thrifty_VLFS_ols==1	//	Currently VLFS
		mat	trans_3by3_mgn_`category'_f_VLFS	=	e(b)
		qui	svy, subpop(`category'): proportion	f1_rho1_thrifty_cat_ols	if	rho1_thrifty_LFS_ols==1		//	Currently LFS
		mat	trans_3by3_mgn_`category'_f_LFS	=	e(b)
		qui	svy, subpop(`category'): proportion	f1_rho1_thrifty_cat_ols	if	rho1_thrifty_FS_ols==1		//	Currently FS
		mat	trans_3by3_mgn_`category'_f_FS	=	e(b)
		
		mat	trans_3by3_mgn_`category'_f	=	trans_3by3_mgn_`category'_f_VLFS	\	trans_3by3_mgn_`category'_f_LFS	\		trans_3by3_mgn_`category'_f_FS		
		mat	trans_3by3_mgn_foodstamp_f	=	nullmat(trans_3by3_mgn_foodstamp_f),	trans_3by3_mgn_`category'_f
		
		*	Joint distribution	(two-way tabulate)
			
			*	Backward (lag)
			svy, subpop(`category'): tabulate l1_rho1_thrifty_cat_ols	rho1_thrifty_cat_ols
			mat	trans_3by3_jnt_`category' = e(b)[1,1], e(b)[1,2], e(b)[1,3]	\ e(b)[1,4], e(b)[1,5],	e(b)[1,6]	\	e(b)[1,7],	e(b)[1,8],	e(b)[1,9]	
			mat	trans_3by3_jnt_foodstamp	=	nullmat(trans_3by3_jnt_foodstamp),	trans_3by3_jnt_`category'
			
			*	Forward
			svy, subpop(`category'): tabulate rho1_thrifty_cat_ols	f1_rho1_thrifty_cat_ols
			mat	trans_3by3_jnt_`category'_f = e(b)[1,1], e(b)[1,2], e(b)[1,3]	\ e(b)[1,4], e(b)[1,5],	e(b)[1,6]	\	e(b)[1,7],	e(b)[1,8],	e(b)[1,9]	
			mat	trans_3by3_jnt_foodstamp_f	=	nullmat(trans_3by3_jnt_foodstamp_f),	trans_3by3_jnt_`category'_f
			
	}
	
	putexcel	set "${PSID_outRaw}/Transition_Matrices", sheet(2by2_characters) modify	/*replace*/
	putexcel	A103	=	matrix(trans_3by3_mgn_foodstamp), names overwritefmt nformat(number_d1)
	putexcel	A108	=	matrix(trans_3by3_jnt_foodstamp), names overwritefmt nformat(number_d1)
	putexcel	A113	=	matrix(trans_3by3_mgn_foodstamp_f), names overwritefmt nformat(number_d1)
	putexcel	A118	=	matrix(trans_3by3_jnt_foodstamp_f), names overwritefmt nformat(number_d1)
	
*	First-order dependence test (3X3)
	cap	mat	drop	trans_9by9
	mat	zeros	=	[0,0,0]
				
	*	Generate state sequence variable (t-2, t-1)
	foreach	cat_lag2	in	VLFS	LFS	FS	{
		foreach	cat_lag1	in	VLFS	LFS	FS	{
			
			cap	drop	PFS_ols_`cat_lag2'_`cat_lag1'
			gen			PFS_ols_`cat_lag2'_`cat_lag1'	=	0	if	!mi(l2_rho1_thrifty_cat_ols)	&	!mi(l1_rho1_thrifty_cat_ols)
			replace		PFS_ols_`cat_lag2'_`cat_lag1'	=	1	if	l2_rho1_thrifty_`cat_lag2'_ols	==	1	&	l1_rho1_thrifty_`cat_lag1'_ols	==	1
			
			svy, subpop(PFS_ols_`cat_lag2'_`cat_lag1'):	proportion	rho1_thrifty_cat_ols	
			if	"`cat_lag1'"=="VLFS"	{
				mat	PFS_ols_`cat_lag2'_`cat_lag1'	=	e(b)[1,1], e(b)[1,2], e(b)[1,3], zeros, zeros
			}
			else	if	"`cat_lag1'"=="LFS"	{
				mat	PFS_ols_`cat_lag2'_`cat_lag1'	=	zeros,e(b)[1,1], e(b)[1,2], e(b)[1,3], zeros
			}
			else	{
				mat	PFS_ols_`cat_lag2'_`cat_lag1'	=	zeros, zeros, e(b)[1,1], e(b)[1,2], e(b)[1,3]
			}
			
			mat	trans_9by9	=	nullmat(trans_9by9)	\	PFS_ols_`cat_lag2'_`cat_lag1'
			
		}	//	lag1
	}	//	lag2
	
	putexcel	A123	=	matrix(trans_9by9), names overwritefmt nformat(number_d1)	


/*
cap drop retireyear_min
cap drop retireyear_max
bys fam_ID_1999: egen retireyear_min = min(retire_year_head) 	if inrange(retire_year_head,1930,2017)
bys fam_ID_1999: egen retireyear_max = max(retire_year_head)	if inrange(retire_year_head,1930,2017)
br fam_ID_1999 year2 emp_status_head retire_year_head retireyear_min retireyear_max if /*fam_ID_1999==31*/ retireyear_min!=retireyear_max